### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by njmdietrich** [ManeraKai/fediredirect#1]
Hi,
I came here from the libredirect issue and am pleasantly surprised that this exists.
It is just lacking documentation at the moment - Which browsers are supported? Is it just Firefox? What fediverse servers are supported? It looks like lemmy, mastodon and pleroma based on the icons found in the assets folder. Most importantly: how do I install it?

**Comment by ManeraKai** [comment]
> Which browsers are supported? Is it just Firefox?

Since FediRedirect doesn't use [https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest](webRequest), it can be manifest v3 so it will be in the chrome web store.

> What fediverse servers are supported?

Currently I added support for Lemmy => Lemmy. I'll add more such as Lemmy => Mastodon, Mastodon => Mastodon, Mastodon => Lemmy and so on.

> Most importantly: how do I install it?

It's your fault you intrigued me to announce early xD, currently it's under review in Mozilla Add-On Store.
