### ISSUE TITLE
Reduce permissions

### ISSUE THREAD

**Issue by martijk** [ManeraKai/fediredirect#2]
I wonder if it's possible to reduce the permissions a bit. I understand that it's not doable to hardcode all fediverse instances into the extension, but [this](https://addons.mozilla.org/en-US/firefox/addon/sci-hub-x-now/) extension somehow manages to work without any permissions (the one that's listed is optional). I'm not familiar with the extension API, but my guess is that you grant it permission to access the current page the moment that you press the button, instead of it working all the time in the background. Since it does something similar to your extension, I wonder if that would work for you too.

**Comment by ManeraKai** [comment]
[sci-hub-now ] has those permissions: https://github.com/gchenfc/sci-hub-now/blob/master/manifest.json#L43-L55
we have those: https://github.com/ManeraKai/fediredirect/blob/main/src/manifest.json#L18-L23
the structure is a bit different since sci-hub-now uses manifest v3 while we use manifest v2.

but to be frank the `tabs` permission should be gone, bc we only use the `activeTab`. I just had it for testing purposes bc somethings weren't working.

> but my guess is that you grant it permission to access the current page the moment that you press the button, instead of it working all the time in the background

Correct.
